### ISSUE TITLE
How to select between FFT and IFFT in your algorithm?

### ISSUE THREAD

**Issue by DanCasterIt** [thasti/fft#1]
Hi, I'm a master degree engegneering student. I've a project in wich I have to implement a 16-bit hardware SPI FFT and IFFT with 128 samples window at time. I'm simulating your code using Quartus II and Altera ModelSim.
In your testbench I can see only an FFT transformation but not an IFFT. Did you implemented it yet? if yes, how do I select wich algorithms to use?
I see in you code these four signals:
d_re
d_im
q_re
q_im
I think that this implementation would do also the IFFT otherwise I can't understand the d_im existance.
I also want to ask you if these warings I obtain simulating your code are normal:
\# ** Warning: NUMERIC_STD.TO_UNSIGNED: vector truncated
\#    Time: 99500 ns  Iteration: 0  Instance: /fft_tb/dut/all_instances(6)/first_stages_only/tf_rom
\# ** Warning: NUMERIC_STD.TO_UNSIGNED: vector truncated
\#    Time: 99700 ns  Iteration: 0  Instance: /fft_tb/dut/all_instances(6)/first_stages_only/tf_rom
\# ** Warning: NUMERIC_STD.TO_UNSIGNED: vector truncated
\#    Time: 99900 ns  Iteration: 0  Instance: /fft_tb/dut/all_instances(6)/first_stages_only/tf_rom
Simulation duration lasts 80.000ns for me. Is it also normal?

Thank you for your attention :)

**Comment by thasti** [comment]
Hi,

The code implements a complex valued FFT, i.e. takes complex input samples and produces complex output samples. This explains the existence of d_im.
The only differences between the definition of DFT and IDFT are a constant scaling factor 1/N and a different sign in the exponential. 
- The constant scaling can be applied afterwards (indeed just as a reinterpretation of the number as a different fixed point format).
- The different sign in the exponential can be accounted for simply by supplying the complex conjugate of the input samples (or using the complex conjugate of the output samples as the IDFT result).

The algorithm itself is exactly the same for DFT and IDFT, and hence also for FFT/IFFT.

I will look into the warnings later. The simulation of the complete input vector should take around 100us in any case.
